// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu88w5N1pGt6H0eJ-Uo6okNt_5DFNAr10',
    appId: '1:135487205985:android:f455f60d0be3698c5d7020',
    messagingSenderId: '135487205985',
    projectId: 'chat-app-b6c53',
    storageBucket: 'chat-app-b6c53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr9i5bYqUh5V1iAe2SHM72IuhEoh1nQTo',
    appId: '1:135487205985:ios:0dba62fd4ba7a58a5d7020',
    messagingSenderId: '135487205985',
    projectId: 'chat-app-b6c53',
    storageBucket: 'chat-app-b6c53.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr9i5bYqUh5V1iAe2SHM72IuhEoh1nQTo',
    appId: '1:135487205985:ios:0dba62fd4ba7a58a5d7020',
    messagingSenderId: '135487205985',
    projectId: 'chat-app-b6c53',
    storageBucket: 'chat-app-b6c53.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDudmWHiBCr0kZdr5UxmGMrG67CeYYeN18',
    appId: '1:135487205985:web:d7fc01b11e090ba75d7020',
    messagingSenderId: '135487205985',
    projectId: 'chat-app-b6c53',
    authDomain: 'chat-app-b6c53.firebaseapp.com',
    storageBucket: 'chat-app-b6c53.appspot.com',
    measurementId: 'G-W9F5RMSE1G',
  );
}
